### ISSUE TITLE
Sistema di autenticazione

### ISSUE THREAD

**Issue by greco-salvatore** [atusghen/ticket-generator#1]
Bisogna creare il sistema di autenticazione a token in modo da poter utilizzare le API solo se si è autenticati (in particolare per le API da smarphone oppure operatore)

**Comment by atusghen** [comment]
in particolare vediamo se lo standard JwDTO ci può essere utile

**Comment by greco-salvatore** [comment]
in particolare guardiamo se lo standard JwDTO ci può essere utile

**Comment by greco-salvatore** [comment]
se può servire, dovrebbe esserci un metodo per impedire generazioni consecutive per lo stesso utente, ma per adesso è apposto
